replicaCount: 1

image:
  repository: axontic.azurecr.io/rdp-status-dashboard
  tag: 1.1.1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  PORT: 3000
  HEARTBEAT_MS: 60000
  OFFLINE_MS: 150000
  CONSOLE_BUSY: "false"
  USE_CLIENT_OCCUPANCY: "true"
