replicaCount: 1

image:
  repository: axontic.azurecr.io/rdp-status-dashboard
  tag: 1.1.1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 443
  targetPort: https
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"

env:
  PORT: 3000
  HEARTBEAT_MS: 60000
  OFFLINE_MS: 150000
  CONSOLE_BUSY: "false"
  USE_CLIENT_OCCUPANCY: "true"

tlsProxy:
  enabled: true
  httpPort: 8080
  secretName: rdp-status-tls
  port: 8443
  hosts:
    - rdp-status.we4it.com
  image:
    repository: nginx
    tag: 1.27-alpine
    pullPolicy: IfNotPresent
