apiVersion: v1
kind: Service
metadata:
  name: {{ include "rdp-status.fullname" . }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "rdp-status.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
